### PR TITLE
contact widget: add email default email subject if no subject defined in form

### LINKED ISSUE #248: Contact: Default Subject doesn't work unless a subject field is present
Introduced as a result of #130 

[This check](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/contact/contact.php#L795) is the only possible time the default subject will be used. The issue here is that It relies on having a subject field that isn't required and has to be empty for the default subject to be used.

The default subject, if applicable, should be used instead of a generated one.

### PR DESCRIPTION
**Pull request by dl4ner**
sorry, I messed up with branches in my local repo, so I had to send this PR again.

it is the same as pull #280 which I messed up due to more commits and so I will close them.

again the info:

if you have multiple contact forms and want to have a fixed subject on each form, this case has not been catched in the code:
- do not define a subject field
- set a default subject field

if subject is not definad and default subject is defined that default subject will be used for the email.

this should basically fix #248

### CODE REVIEW

File: widgets/contact/contact.php [hunk 1]
```diff
@@ -832,6 +832,11 @@ function contact_form_action( $instance, $storage_hash ){
 			}
 		}
 
+		// Add in the default subject if no subject field is defined in the form at all
+		if ( !isset( $email_fields['subject'] ) && !empty($instance['settings']['default_subject']) ) {
```
Comment (AlexGStapleton) [inline widgets/contact/contact.php]: Would it be possible to space the second brackets to conform with [WordPress PHP coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage)?

**Comment by gregpriday** [comment]
Thanks for the addition @dl4ner!
